# Generated by Django 4.1.9 on 2023-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patty', models.CharField(default='', max_length=20)),
                ('firstIngredient', models.CharField(default='', max_length=25)),
                ('secondIngredient', models.CharField(default='', max_length=25)),
                ('thirdIngredient', models.CharField(default='', max_length=25)),
                ('fourthIngredient', models.CharField(default='', max_length=25)),
                ('lettuce', models.CharField(default='', max_length=10)),
                ('tomato', models.CharField(default='', max_length=10)),
                ('onion', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
